global:
  scrape_interval: 5s  # take data every 5 seconds
  evaluation_interval: 5s  # evaluate rules every 5 seconds
 
scrape_configs:
  - job_name: 'ml_model_exporter'
    static_configs:
      - targets: ['exporter:8000']